spring:
  application:
    name: backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres_db
    username: postgres_admin
    password: 654244141
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  private-key-path: src/main/resources/keys/private.pem
  public-key-path: src/main/resources/keys/public.pem

server:
  port: 8080